package com.mycompany.trycatch1;
import java.util.Scanner;
public class trycatch1 
{
    public static void main(String[] args) 
    {
        Scanner nn=new Scanner(System.in);
        int a,b,z;
        System.out.print("Enter the first number :");
        a=n.nextInt();
        System.out.print("Enter the second number :");
        b=n.nextInt();
        
        try
        {
            z=a/b;
            System.out.println("Aswer is :"+z);
        }
        catch(ArithmeticException e)
        {
            System.out.println("Can't divided by Zero");
        }
    }
}

package com.mycompany.trycatch2;
public class trycatch2
{
    public static void main(String[] args)
    {
        int array[]=new int[6];
        try
        {
            array[6]=44;
            System.out.println("Array value is :"+array[6]);
        }
        catch(ArrayIndexOutOfBoundsException e)
        {
            System.out.println("Out of the array size");
        }
    }
}

